# Generated by Django 2.0.3 on 2021-07-16 08:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthInformation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batuk', models.BooleanField(default=False, verbose_name='Batuk-batuk')),
                ('demam', models.BooleanField(default=False, verbose_name='Demam')),
                ('sakit_kepala', models.BooleanField(default=False, verbose_name='Sakit Kepala')),
                ('hilang_bau', models.BooleanField(default=False, verbose_name='Hilang Bau dan Rasa')),
                ('sukar_bernafas', models.BooleanField(default=False, verbose_name='Kesukaran Bernafas')),
                ('lain_lain', models.TextField(null=True, verbose_name='Lain-lain')),
                ('status_pelancongan', models.BooleanField(default=False)),
                ('lokasi_pelancongan', models.CharField(max_length=50, null=True)),
                ('status_kontak_rapat', models.BooleanField(default=False)),
                ('group_kontak_rapat', models.CharField(blank=True, choices=[('A', 'group a'), ('B', 'group b'), ('C', 'group c')], default='C', max_length=1, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
