# Generated by Django 2.0.3 on 2021-07-16 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthinformation',
            name='lain_lain',
            field=models.TextField(blank=True, null=True, verbose_name='Lain-lain'),
        ),
        migrations.AlterField(
            model_name='healthinformation',
            name='lokasi_pelancongan',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
