# Generated by Django 2.0.3 on 2021-07-16 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premise', '0002_mockscanevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockscanevent',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
