# Generated by Django 2.0.3 on 2021-07-16 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinestatus',
            name='vplace',
            field=models.CharField(blank=True, choices=[('UM', 'University Malaya'), ('MV', 'MidValley'), ('PWTC', 'PWTC'), ('BJL', 'Bukit Jalil')], default='UM', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vaccinestatus',
            name='vtype',
            field=models.CharField(blank=True, choices=[('ASTRAZENECA', 'AstraZeneca'), ('PFIZER', 'PFizer'), ('SINOVAC', 'SINOVAC')], default='PFIZER', max_length=100, null=True),
        ),
    ]
